import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Nav from "@/components/NavBar";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { State } from "../util/state";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const router = useRouter();

	useEffect(() => {
		// Check if user is not logged in
		// If so, redirect to login page
		const user = State.get("user");
		if (!user) {
			router.push("/login");
		}
	}, []);

	return (
		<>
			<Head>
				<title>NeuroNote</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Nav />
			</main>
		</>
	);
}
